export const ALERT = "ALERT";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const FETCH_USER = "FETCH_USER";

export const FETCH_DASHBOARD_DETAILS = "FETCH_DASHBOARD_DETAILS";
export const SUBMIT_ARTICLE = "SUBMIT_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const SEARCH_ARTICLES = "SEARCH_ARTICLES";
export const POST_COMMENT = "POST_COMMENT";
export const ADVANCE_PAGE = "ADVANCE_PAGE";
